// src/lib/components/MenuBar.svelte
<script lang="ts">
	import type { LinkShareUnion } from '$lib/types';
	import { codeState } from '$lib/code-state.svelte';
	import Button from '$lib/components/ui/button/button.svelte';
	import * as Popover from '$lib/components/ui/popover/index.js';
	import { Separator } from '$lib/components/ui/separator/index.js';
	import { useIsMobile, useIsShared } from '$lib/hooks.svelte';
	import { localStore } from '$lib/utils';
	import {
		EllipsisIcon,
		CodeIcon,
		LinkIcon,
		PencilIcon,
		ShareIcon,
		Trash2Icon
	} from '@lucide/svelte';
	import { Micro } from 'effect';
	import { haptic } from 'ios-haptics';
	import { toast } from 'svelte-sonner';
	import { copyLink } from '../sharing';
	import AppearanceToggle from './AppearanceToggle.svelte';
	import LangSwitcher from './LangSwitcher.svelte';
	import RunButton from './RunButton.svelte';

	const isMobile = useIsMobile();
	const isShared = useIsShared();

	let title = $state('');
</script>

<div class="flex items-center justify-between gap-2 p-4">
	<div class="flex items-center gap-3">
		<div class="flex items-center gap-2">
			<Popover.Root>
				<Popover.Trigger>
					<Button size="icon" variant="outline" aria-label="Toggle menu" onclick={haptic}>
						<EllipsisIcon size={16} />
						<span class="sr-only">Menu</span>
					</Button>
				</Popover.Trigger>

				<Popover.Content align="start">
					<div class="flex flex-col gap-2">
						<div class="flex items-center justify-between">
							<h1>Webground</h1>
							<AppearanceToggle />
						</div>

						<Separator class="my-2" />

						<Button class="w-full" href="https://github.com/tijnjh/webground">
							<CodeIcon size={16} />
							View source
						</Button>

						{#if !isShared}
							<Separator class="my-2" />
							<Popover.Root>
								<Popover.Trigger>
									<Button class="w-full" variant="destructive" onclick={haptic}>
										<Trash2Icon size={16} />
										Clear all code
									</Button>
								</Popover.Trigger>
								<Popover.Content align="start">
									<p class="mb-2">Are you sure you want to your clear your code?</p>

									<Separator class="my-4" />

									<Popover.Close class="w-full">
										<Button
											class="w-full"
											variant="destructive"
											onclick={() => {
												haptic();
												codeState.clear();
												toast.success('Cleared code');
											}}
										>
											Confirm
										</Button>
									</Popover.Close>
								</Popover.Content>
							</Popover.Root>
						{/if}
					</div>
				</Popover.Content>
			</Popover.Root>

			<Popover.Root>
				<Popover.Trigger>
					<Button variant="outline" onclick={haptic}>
						<ShareIcon size={16} />
						Share
					</Button>
				</Popover.Trigger>
				<Popover.Content align="start">
					<div class="flex flex-col gap-2">
						<h3>Link sharing</h3>

						<Separator class="my-2" />

						{@render shareButton('full', 'Full URL')}

						<Separator class="my-2" />

						<label class="mb-2 flex items-center justify-between gap-4">
							<span>Title</span>
							<input
								type="text"
								placeholder="Shared code"
								class="min-w-0 text-right outline-none"
								bind:value={title}
							/>
						</label>

						{@render shareButton('markdown', 'Markdown')}
						{@render shareButton('html', 'HTML')}
					</div>
				</Popover.Content>
			</Popover.Root>
		</div>
	</div>

	{#if !isMobile}
		<LangSwitcher />
	{/if}

	<div class="flex items-center gap-2">
		{#if isShared}
			<Button
				onclick={() => {
					Micro.runSync(localStore('code', codeState.current));
					location.href = location.href.split('?')[0];
				}}
			>
				<PencilIcon size={16} />
				Edit
			</Button>
		{/if}

		{#if !isMobile}
			<RunButton />
		{/if}
	</div>
</div>

{#snippet shareButton(mode: LinkShareUnion, label: string)}
	<Popover.Close>
		<Button
			onclick={() => {
				Micro.runPromise(copyLink({ mode, title }))
					.then((res) => {
						haptic.confirm();
						toast.success(`Copied link (${mode}) to clipboard`);

						if (res.isLong) {
							setTimeout(() => {
								toast.warning(
									'URL is longer than 2048 characters, which might cause issues in certain browsers'
								);
							}, 300);
						}
					})
					.catch((error) => {
						haptic.error();
						toast.error(error.message);
					});
			}}
			class="w-full"
		>
			<LinkIcon size={16} />
			{label}
		</Button>
	</Popover.Close>
{/snippet}

// src/components/menu-bar.tsx
import type { ReactNode } from 'react'
import type { LinkShareUnion } from '#lib/types'
import { Effect } from 'effect'
import { hapticTrigger } from 'ios-haptics'
import { CodeIcon, EllipsisIcon, LinkIcon, PencilIcon, ShareIcon, Trash2Icon } from 'lucide-react'
import { useState } from 'react'
import { toast } from 'sonner'
import { useCodeStore } from '#lib/atoms/code'
import { useIsMobile, useIsShared } from '#lib/hooks'
import { copyLink } from '#lib/sharing'
import { localStore } from '#lib/utils'
import { LangSwitcher } from './lang-switcher'
import { RunButton } from './run-button'
import { Button } from './ui/button'
import { Popover, PopoverContent, PopoverTrigger } from './ui/popover'
import { Separator } from './ui/separator'

export function MenuBar() {
  const isMobile = useIsMobile()
  const isShared = useIsShared()

  const [title, setTitle] = useState('')

  const { code, clearCode } = useCodeStore()

  return (
    <div className="flex items-center justify-between gap-2 p-4">
      <div className="flex items-center gap-3">
        <div className="flex items-center gap-2">
          <Popover>
            <PopoverTrigger>
              <Button size="icon" variant="outline" aria-label="Toggle menu" ref={hapticTrigger}>
                <EllipsisIcon size={16} />
                <span className="sr-only">Menu</span>
              </Button>
            </PopoverTrigger>

            <PopoverContent align="start">
              <div className="flex flex-col gap-2">

                <div className="flex items-center justify-between">
                  <h1>Webground</h1>
                  {/* <AppearanceToggle /> */}
                </div>

                <Separator className="my-2" />

                <Button className="w-full" render={<a href="https://github.com/tijnjh/webground" />}>
                  <CodeIcon size={16} />
                  View source
                </Button>

                {isShared && (
                  <>
                    <Separator className="my-2" />

                    <Popover>
                      <PopoverTrigger>
                        <Button className="w-full" variant="destructive" ref={hapticTrigger}>
                          <Trash2Icon size={16} />
                          Clear all code
                        </Button>
                      </PopoverTrigger>
                      <PopoverContent align="start">
                        <p className="mb-2">Are you sure you want to your clear your code?</p>

                        <Separator className="my-4" />

                        <Button
                          className="w-full"
                          variant="destructive"
                          onClick={() => {
                            clearCode()
                            toast.success('Cleared code')
                          }}
                        >
                          Confirm
                        </Button>

                      </PopoverContent>
                    </Popover>
                  </>
                )}
              </div>
            </PopoverContent>
          </Popover>

          <Popover>
            <PopoverTrigger>
              <Button variant="outline" ref={hapticTrigger}>
                <ShareIcon size={16} />
                Share
              </Button>
            </PopoverTrigger>
            <PopoverContent align="start">
              <div className="flex flex-col gap-2">
                <h3>Link sharing</h3>

                <Separator className="my-2" />

                <ShareButton mode="full" title={title}>Full URL</ShareButton>

                <Separator className="my-2" />

                <label className="mb-2 flex items-center justify-between gap-4">
                  <span>Title</span>
                  <input
                    type="text"
                    placeholder="Shared code"
                    className="min-w-0 text-right outline-none"
                    value={title}
                    onChange={e => setTitle(e.currentTarget.value)}
                  />
                </label>

                <ShareButton mode="markdown" title={title}>Markdown</ShareButton>
                <ShareButton mode="html" title={title}>HTML</ShareButton>

              </div>
            </PopoverContent>
          </Popover>
        </div>
      </div>

      {!isMobile && (
        <LangSwitcher />
      )}

      <div className="flex items-center gap-2">
        {isShared && (
          <Button
            onClick={() => {
              Effect.runSync(localStore('code', code))
              location.href = location.href.split('?')[0]
            }}
          >
            <PencilIcon size={16} />
            Edit
          </Button>
        )}

        {!isMobile && (
          <RunButton />
        )}
      </div>
    </div>
  )
}

function ShareButton({
  mode,
  children,
  title,
}: {
  mode: LinkShareUnion
  children: ReactNode
  title: string
}) {
  return (
    <Button
      onClick={() => {
        Effect.runPromise(copyLink({ mode, title }))
          .then((res) => {
            toast.success(`Copied link (${mode}) to clipboard`)

            if (res.isLong) {
              setTimeout(() => {
                toast.warning(
                  'URL is longer than 2048 characters, which might cause issues in certain browsers',
                )
              }, 300)
            }
          })
          .catch((error) => {
            toast.error(error.message)
          })
      }}
      className="w-full"
    >
      <LinkIcon size={16} />
      {children}
    </Button>
  )
}
