// src/lib/components/Preview.svelte
<script lang='ts' module>
  import type { Code } from '../types'
  import { template } from '$lib/preview/template'
  import { cn, localStore } from '$lib/utils'
  import { Micro } from 'effect'

  let src = $state('/start.html')

  export function updatePreview(code: Code): Micro.Micro<{ didUpdate: boolean }, Error> {
    return Micro.gen(function* () {
      if (Object.values(code).every(v => v.trim() === '')) {
        src = '/start.html'
        return { didUpdate: false }
      }

      const url = Micro.try({
        try: () => {
          const blob = new Blob([template(code)], { type: 'text/html' })
          return URL.createObjectURL(blob)
        },
        catch: () => new Error('failed to create object url'),
      })

      src = yield* url

      yield* localStore('code', code)

      return { didUpdate: true }
    })
  }
</script>

<script lang='ts'>
  const props: { class?: string } = $props()
</script>

<iframe
  {src}
  title='preview'
  class={cn('bg-white border-0', props.class)}
  referrerpolicy='no-referrer'
  sandbox='allow-modals allow-downloads allow-scripts allow-forms'
>
</iframe>

// src/components/preview.tsx
import { Effect } from 'effect'
import { useEffect, useState } from 'react'
import { useCodeStore } from '#lib/atoms/code'
import { template } from '#lib/preview/template'
import { cn, localStore } from '#lib/utils'

export function Preview({ className }: { className?: string }) {
  const { src } = usePreview()

  return (
    <iframe
      src={src}
      title="preview"
      className={cn('border-0 bg-white', className)}
      referrerPolicy="no-referrer"
      sandbox="allow-modals allow-downloads allow-scripts allow-forms"
    />
  )
}

export function usePreview() {
  const [src, setSrc] = useState('/start.html')

  useEffect(() => {
    return () => {
      if (src.startsWith('blob:')) {
        URL.revokeObjectURL(src)
      }
    }
  }, [src])

  const { code } = useCodeStore()

  const updatePreview = Effect.fn(function* () {
    if (Object.values(code).every(v => v.trim() === '')) {
      setSrc('/start.html')
      return { didUpdate: false }
    }

    const url = Effect.try({
      try: () => {
        const blob = new Blob([template(code)], { type: 'text/html' })
        return URL.createObjectURL(blob)
      },
      catch: () => new Error('failed to create object url'),
    })

    setSrc(yield* url)

    yield* localStore('code', code)

    return { didUpdate: true }
  })

  return {
    src,
    updatePreview,
  }
}
