// src/App.tsx
import type { Code } from '#lib/types'
import { Effect } from 'effect'
import { hapticTrigger } from 'ios-haptics'
import { useAtomValue } from 'jotai'
import { ChevronUpIcon } from 'lucide-react'
import { useEffect, useState } from 'react'
import { toast, Toaster } from 'sonner'
import { useEventListener } from 'usehooks-ts'
import { Console } from '#components/console'
import { Editor } from '#components/editor'
import { LangSwitcher } from '#components/lang-switcher'
import { Preview, usePreview } from '#components/preview'
import { RunButton } from '#components/run-button'
import { Button } from '#components/ui/button'
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from '#components/ui/resizable'
import { useCodeStore } from '#lib/atoms/code'
import { selectedTabAtom } from '#lib/atoms/globals'
import { decode } from '#lib/codec'
import { useIsMobile, useIsShared } from '#lib/hooks'
import { cn, extractCodeParams, localStore, setTabFromHash } from '#lib/utils'

export function App() {
  const { code, setCode } = useCodeStore()
  const selectedTab = useAtomValue(selectedTabAtom)

  const isMobile = useIsMobile()
  const isShared = useIsShared()

  const { updatePreview } = usePreview()

  const [showMobilePreview, setShowMobilePreview] = useState(false)

  useEffect(() => {
    const fn = async () => {
      if (isShared) {
        const { h, c, j } = extractCodeParams()

        const decoded = await Effect.runPromiseExit(
          Effect.all(
            [
              h ? decode(h) : Effect.succeed(''),
              c ? decode(c) : Effect.succeed(''),
              j ? decode(j) : Effect.succeed(''),
            ],
            { concurrency: 3 },
          ),
        )

        if (decoded._tag === 'Failure') {
          toast.error(decoded.cause.reasons.map(r => r.toString()).join(', '))
          console.error(decoded.cause)
          return
        }

        const [html, css, js] = decoded.value

        setCode({ html, css, js })
      }
      else {
        const codeResult = await Effect.runPromiseExit(localStore<Code>('code') || {})

        if (codeResult._tag === 'Success') {
          const code = codeResult.value
          for (const [key, val] of Object.entries(code)) {
            setCode(prev => ({ ...prev, [key]: val }))
          }
        }
        else {
          console.error('Failed to retrieve code from localStorage:', codeResult.cause)
        }
      }

      setTabFromHash(selectedTab, code)
    }

    fn()
  // eslint-disable-next-line react/exhaustive-deps
  }, [])

  useEventListener('hashchange', () => {
    setTabFromHash(selectedTab, code)
  })

  useEventListener('keydown', async (e) => {
    if ((e.metaKey || e.ctrlKey) && (e.key === 's' || e.key === 'Enter')) {
      e.preventDefault()
      await Effect.runPromise(updatePreview())
    }
  })

  if (!isMobile) {
    return (
      <ResizablePanelGroup>
        <ResizablePanel>
          <Editor />
        </ResizablePanel>

        <ResizableHandle />

        <ResizablePanel>
          <div className="flex h-full flex-col">
            <Preview className="size-full grow" />
            <Console />
          </div>
        </ResizablePanel>
      </ResizablePanelGroup>
    )
  }

  return (
    <>

      <div className="grid h-dvh grid-rows-[1fr_min-content]">
        <Editor />

        <LangSwitcher className="fixed bottom-20 left-4 bg-white dark:bg-[#1e1e1e]" />

        <div className="flex items-center justify-between border-t bg-white p-4 dark:bg-[#1e1e1e]">
          <Button
            ref={hapticTrigger}
            onClick={() => {
              setShowMobilePreview(prev => !prev)
            }}
          >
            <div
              className={cn(
                'transition-transform',
                showMobilePreview && 'rotate-x-180',
              )}
            >
              <ChevronUpIcon />
            </div>
            Preview
          </Button>
          <RunButton />
        </div>
      </div>

      {showMobilePreview && (
        <div className="fixed top-17 bottom-17 isolate flex w-full flex-col">
          <Preview className="grow" />
          <Console />
        </div>
      )}

      <Toaster richColors position={isMobile ? 'top-center' : 'bottom-right'} />
    </>
  )
}

// src/App.svelte
<script lang="ts">
  import { Toaster } from "svelte-sonner";
  import { Pane, PaneGroup, PaneResizer } from "paneforge";
  import { ChevronUpIcon } from "@lucide/svelte";
  import { onMount } from "svelte";

  import type { Code, LangUnion } from "./lib/types";
  import Preview, { updatePreview } from "./lib/components/Preview.svelte";
  import Editor from "./lib/components/Editor.svelte";
  import LangSwitcher from "./lib/components/LangSwitcher.svelte";
  import { haptic } from "ios-haptics";
  import { isMobile, isShared } from "./lib/helpers";
  import { decode } from "./lib/codec";

  let currentTab: LangUnion = $state("html");
  let showMobilePreview = $state(false);

  let code: Code = $state({
    html: "",
    css: "",
    js: "",
  });

  function setTabFromHash() {
    const hash = window.location.hash.replace("#", "");

    if (Object.keys(code).includes(hash)) {
      currentTab = hash as keyof Code;
    }
  }

  onMount(() => {
    if (isShared) {
      const params = new URL(location.href).searchParams;

      const h = params.get("h");
      const c = params.get("c");
      const j = params.get("j");

      code = {
        html: h ? decode(h) : "",
        css: c ? decode(c) : "",
        js: j ? decode(j) : "",
      };
    } else {
      if (localStorage.code) {
        for (
          const [key, val] of Object.entries(
            JSON.parse(localStorage.code),
          )
        ) {
          code[key as keyof Code] = val as string;
        }
      }
    }

    setTabFromHash();
    window.addEventListener("hashchange", setTabFromHash);
    return () => window.removeEventListener("hashchange", setTabFromHash);
  });
</script>

<svelte:window
  onkeydown={(e) => {
    if ((e.metaKey || e.ctrlKey) && (e.key === "s" || e.key === "Enter")) {
      e.preventDefault();
      updatePreview(code);
    }
  }}
/>

{#if !isMobile}
  <!-- desktop layout -->
  <PaneGroup direction="horizontal">
    <Pane defaultSize={50} class="h-svh">
      <Editor bind:code {currentTab} />
    </Pane>

    <PaneResizer class="place-items-center grid bg-zinc-800 w-4">
      <span class="bg-zinc-600 rounded-full w-1 h-12"></span>
    </PaneResizer>

    <Pane defaultSize={50}>
      <Preview />
    </Pane>
  </PaneGroup>
{:else}
  <!-- mobile layout -->
  <div class="grid grid-rows-[1fr_3rem] h-svh">
    <Editor bind:code {currentTab} />

    <div class="flex justify-between items-center bg-[#1e1e1e] pr-2 border-zinc-700 border-t">
      <LangSwitcher bind:currentTab />
      <button
        onclick={() => {
          haptic();
          showMobilePreview = !showMobilePreview;
        }}
        class="bg-white text-black btn"
      >
        <div
          class="transition-transform"
          class:rotate-x-180={showMobilePreview}
        >
          <ChevronUpIcon />
        </div>
        Preview
      </button>
    </div>
  </div>

  {#if showMobilePreview}
    <Preview />
  {/if}
{/if}

<Toaster richColors />
