// src/components/appearance-toggle.tsx
import { MoonIcon, SunIcon } from 'lucide-react'
import { useTheme } from 'next-themes'
import { Button } from './ui/button'

export function AppearanceToggle() {
  const { theme, setTheme } = useTheme()

  const toggle = () =>
    theme === 'dark'
      ? setTheme('light')
      : setTheme('dark')

  return (
    <Button
      onClick={toggle}
      variant="outline"
      size="icon"
    >
      <SunIcon
        className="h-[1.2rem] w-[1.2rem] scale-100 rotate-0 transition-all! dark:scale-0 dark:-rotate-90"
      />
      <MoonIcon
        className="absolute h-[1.2rem] w-[1.2rem] scale-0 rotate-90 transition-all! dark:scale-100 dark:rotate-0"
      />
      <span className="sr-only">Toggle theme</span>
    </Button>
  )
}

// src/lib/components/AppearanceToggle.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button/index.js';
	import MoonIcon from '@lucide/svelte/icons/moon';
	import SunIcon from '@lucide/svelte/icons/sun';
	import { mode, toggleMode } from 'mode-watcher';
	import { setTheme } from './Monaco.svelte';
</script>

<Button
	onclick={() => {
		toggleMode();
		if (!mode.current) return;
		setTheme(`vs-${mode.current}`);
	}}
	variant="outline"
	size="icon"
>
	<SunIcon
		class="h-[1.2rem] w-[1.2rem] scale-100 rotate-0 transition-all! dark:scale-0 dark:-rotate-90"
	/>
	<MoonIcon
		class="absolute h-[1.2rem] w-[1.2rem] scale-0 rotate-90 transition-all! dark:scale-100 dark:rotate-0"
	/>
	<span class="sr-only">Toggle theme</span>
</Button>
