// src/components/lang-switcher.tsx
import type { LangUnion } from '#lib/types'
import { hapticTrigger } from 'ios-haptics'
import { useAtomValue, useSetAtom } from 'jotai'
import { useEffect, useState } from 'react'
import { selectedTabAtom } from '#lib/atoms/globals'
import { ToggleGroup, ToggleGroupItem } from './ui/toggle-group'

export function LangSwitcher({ className }: { className?: string }) {
  const hash = String(location.hash).replace('#', '') // maybe not needed to wrap with string?
  const validHash: LangUnion = hash === 'html' || hash === 'css' || hash === 'js' ? hash : 'html'

  const [value, setValue] = useState<LangUnion>(validHash)

  const setSelectedTab = useSetAtom(selectedTabAtom)

  useEffect(() => {
    location.hash = `#${value}`
    setSelectedTab(value)
  }, [value, setSelectedTab])

  return (
    <ToggleGroup
      variant="outline"
      value={[value]}
      onValueChange={([v]) => setValue(v as LangUnion)}
      className={className}
    >
      <LangTab lang="html" />
      <LangTab lang="css" />
      <LangTab lang="js" />
    </ToggleGroup>
  )
}

function LangTab({ lang }: { lang: LangUnion }) {
  const selectedTab = useAtomValue(selectedTabAtom)

  return (
    <ToggleGroupItem
      ref={selectedTab !== lang ? hapticTrigger : undefined}
      onClick={(e) => {
        if (selectedTab === lang) {
          e.preventDefault()
        }
      }}
      value={lang}
      className="px-6"
    >
      {lang}
    </ToggleGroupItem>
  )
}

// src/lib/components/LangSwitcher.svelte
<script lang='ts'>
  import type { LangUnion } from '$lib/types'
  import { browser } from '$app/environment'
  import * as ToggleGroup from '$lib/components/ui/toggle-group/index.js'
  import { µ } from '$lib/global.svelte'
  import { haptic } from 'ios-haptics'

  const props: { class?: string } = $props()

  const hash = browser ? location.hash.replace('#', '') : ''

  const validHash: LangUnion
    = hash === 'html' || hash === 'css' || hash === 'js' ? hash : 'html'

  let value: LangUnion = $state(validHash)

  $effect(() => {
    location.hash = `#${value}`
    µ.currentTab = value
  })
</script>

<ToggleGroup.Root
  variant='outline'
  type='single'
  bind:value
  class={props.class}
>
  {@render langTab('html')}
  {@render langTab('css')}
  {@render langTab('js')}
</ToggleGroup.Root>

{#snippet langTab(lang: LangUnion)}
  <ToggleGroup.Item
    onclick={(e) => {
      if (µ.currentTab !== lang) {
        haptic()
      }
      else {
        e.preventDefault()
      }
    }}
    value={lang}
    class='px-6'
  >
    {lang}
  </ToggleGroup.Item>
{/snippet}
